### ISSUE TITLE
How to provide headers to mailprod ?

### ISSUE THREAD

**Issue by dan361** [shivylp/mailprod#1]
Hi,

I'm trying to set up mass email delivery with mailprod. I need to send headers for unsubscribing etc. How do I do that ?

I tried to add it simply to functions.py:

`for header_elem in header_elems:
            mail.add_header('Return-Path', 'Precedence', 'List-Help', 'List-Unsubscribe')
`

I have to confess that I'm not very experienced in python, so I could need a little bit help here :)

thanks

**Comment by shivylp** [comment]
Hi !,
I have added support for headers. Take a look at `examples/template2.xml` to understand how to add headers to the template. `mail.add_header(name, value, **params)` is also there now.  Also, mailprod is should work with Python3 as well.
